config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  mount ActionCable.server => '/cable'
  devise_for :users,path_names: {sign_in:'login',sign_out:'logout',sign_up:'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants, only: [:index, :show] do
  resources :comments, only: [:create, :destroy]
  collection do
    get :feeds
    get :ranking
  end
  member do
    get :dashboard
    post :favorite
    post :unfavorite
    post :like
    post :unlike
  end
end
resources :categories, only: :show

resources :users, only: [:index, :update, :show, :edit] do
  member do
    get :friend_list
  end
end


resources :followships, only: [:create, :destroy]

resources :friendships, only: [:create, :destroy]

root "restaurants#index"
namespace :admin do
    root "restaurants#index"
    resources :restaurants
    resources :categories 
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name
has_many :restaurants, dependent: :restrict_with_error




end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :user
belongs_to :restaurant




end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord

  validates :following_id, uniqueness: { scope: :user_id}




  belongs_to :user
  belongs_to :following, class_name: "User"




end

app/models/friendship.rb
class Friendship < ApplicationRecord

  validates :friend_id, uniqueness: { scope: :user_id}

  belongs_to :user
  belongs_to :friend, class_name: "User"




end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category
  has_many :comments  , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user






  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


  def count_favorites
    self.favorite_count = self.favorites.size
    self.save
  end


  def is_liked?(user)
    self.liked_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


mount_uploader :avatar, AvatarUploader
# 「使用者評論很多餐廳」的多對多關聯
has_many :comments, dependent: :restrict_with_error
has_many :restaurants, through: :comments
 # 「使用者收藏很多餐廳」的多對多關聯
has_many :favorites, dependent: :destroy
has_many :favorited_restaurants, through: :favorites, source: :restaurant

has_many :lkes, dependent: :destroy
has_many :liked_restaurants, through: :likes, source: :restaurant 
 # 「使用者追蹤使用者」的 self-referential relationships 設定
 # 不需要另加 source，Rails 可從 Followship Model 設定來判斷 followings 指向 User Model
has_many :followships, dependent: :destroy
has_many :followings, through: :followships
 # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
has_many :inverse_followships, class_name: "Followship",foreign_key: "following_id"
has_many :followers, through: :inverse_followships, source: :user

has_many :friendships, dependent: :destroy
has_many :friends, through: :friendships

has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id" #反向的交友關係 fk為friend_id

has_many :inverse_friends, through: :inverse_friendships, source: :user #加我好友的人



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def admin?
    self.role == "admin"
  
    end

    def following?(user)
      self.followings.include?(user)
    end

    def friending?(user)
      self.friends.include?(user)

    end

    

    def all_friends?(user)
      self.friends.include?(user) || self.inverse_friends.include?(user)
    end

    def friends?(user)
    self.friends.include?(user)
    end
    def inverse_friends?(user)
      self.inverse_friends.include?(user)
    end

    
    def friends_list
    list = []
    self.friends.each do |friend|
      list<<friend if self.inverse_friends.include?(friend)
    end
    return list
    end 


validates_presence_of :name
 
    def first_name
       self.name.split.first
    end
    def last_name
     self.name.split.last_name
    end







end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include DeviseWhitelist

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
      redirect_to restaurant_path(@restaurant)
    end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])      
    @comment.destroy
    redirect_to restaurant_path(@restaurant)
    
  end



    private

    def comment_params
      params.require(:comment).permit(:content)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :friend_list]
  
  def index
  @users= User.all
  
  end 



  def show 
    @commented_restaurants = @user.restaurants
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers  =@user.followers
    @friends = @user.friends_list
    @inverse_friends =  @user.inverse_friends
  end


  def edit

    unless @user ==current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  def friend_list
     @friends = @user.friends
     @inverse_friends =  @user.inverse_friends
  end
  def friend_list
    @user = User.find(params[:id])
    # @all_friends = @user.all_friends
    @friends_list = @user.friends_list
    @sendrequests = @user.friends - @friends_list
    #去除已經加入好友的名單
    @getrequests = @user.inverse_friends - @friends_list
    #去除已經加入好友的名單
  end

  private

    def set_user
      @user = User.find(params[:id])
    end


    def user_params
      params.require(:user).permit(:name, :intro, :avator)
    end

  



 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
   <div class="row">
 
     <div class="col-md-6 col-md-offset-3">
 
       <h3>Edit Profile</h3>
 
       <%= form_for @user do |f| %>
         <div class="form-group">
           <%= f.label :name, "Name" %>
           <%= f.text_field :name, class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.label :intro, "自我介紹" %>
           <%= f.text_area :intro, class: "form-control" %>
           <div class="form-group">
           <%= f.label :avatar, "大頭照上傳" %>
           <%= image_tag @user.avatar if @user.avatar? %>
           <%= f.file_field :avatar %>
          </div>
         </div>
         <div class="form-group">
           <%= f.submit "Update", class: "btn btn-primary" %>
           <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
         </div>
       <% end %>
 
     </div>
 
   </div>
 </div>

app/views/users/friend_list.html.erb
<div class="container">
  <div class="row u-padding-top-40px">
    <!-- avatar -->
    <div class="col-md-4">
      <div class="user-avatar">
        <div class="imgbox">
          <div class="imgbox-inner">
              <div class="image" style="background-image:url('<%=@user.avatar%>')">
              </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="user-content">
      <h2><%=@user.name %></h2>
        <div class="user-profile-email "> 
          <%=@user.email %>
          <ul class="nav nav-pills">
            <li role="presentation" >
              <%=link_to "關於", user_path(@user)%></li>
            <li role="presentation" class="active">
              <a>朋友</a>            
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <h1><%=@user.name%> 和他的好友們</h1>
    <div class="row u-padding-top-40px">
      <%=render partial: "shared/user_list", locals:{users: @friends_list} %>
    </div>
  </div>
  <% if @user == current_user %>
  <div class="row">
    <h1>送出邀請中的名單</h1>
    <div class="row u-padding-top-40px">
      <%=render partial: "shared/user_list", locals:{users: @sendrequests} %>
    </div>
  </div>
  <div class="row">
    <h1>邀請你成為好友</h1>
    <div class="row u-padding-top-40px">
      <%=render partial: "shared/user_list", locals:{users: @getrequests} %>
    </div>
  </div>
  <%end%>
</div>

app/views/users/index.html.erb
 <div class="container">
   <div class="row">
    <ul class="nav nav-tabs">
       <li role="presentation" >
         <%= link_to '首頁', root_path %>
       </li>
       <li role="presentation">
         <%= link_to '最新動態' %>
       </li>
       <li role="presentation">
         <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
       </li>
       <li role="presentation" class="active">
         <%= link_to '美食達人', users_path %>
       </li>
     </ul>
  
 
   </div>
 </div>
 
 <div class="container">
   <div class="row">
 
     <div class="col-md-12">
       <div class="page-header">
         <h1>美食達人</h1>
       </div>
     </div>
 
     <% @users.each do |user| %>
       <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
 
         <%= link_to user_path(user) do %>
           <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
           <%= image_tag(user.avatar, class: "img-rounded") %>
           <h4><%= user.name %></h4>
         <% end %>
 
         <%= render partial: "shared/follow", locals: {user: user} %>
         <%= render partial: "shared/friend", locals: {user: user} %>
 
       </div>
     <% end %>
 
   </div>
 </div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">

        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <!-- inline & unstyled 的 list -->
          <ul class="list-unstyled list-inline">
            <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</li>
            <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</li>
            <li><strong><%= @followings.count %></strong> followings</li>
            <li><strong><%= @followers.count %></strong> followers</li>
            <li><strong><%= @friends.count %></strong>  好友人數</li>
          </ul>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
            <%= link_to 'My friends', friend_list_user_path(@user), class: "btn btn-info" %>
          <% end %>
        </div>
        <div class="clearfix"></div>

      </div>

      <br>

      <div class="col-md-4">
        <!-- 顯示followings的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followings.count %></strong> followings</h3>
          </div>

          <ul class="list-group">
            <% @followings.each do |following| %>
            <li class="list-group-item">
              <%= link_to user_path(following) do %>
              <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %>
              <%= following.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

        <!-- 顯示followers的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followers.count %></strong> followers</h3>
          </div>

          <ul class="list-group">
            <% @followers.each do |follower| %>
            <li class="list-group-item">
              <%= link_to user_path(follower) do %>
              <%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %>
              <%= follower.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-8">

        <!-- 顯示已評論餐廳的清單，panel包一個panel-body裡面使用row>col的layouts來顯示評論 -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
          </div>
          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
            <%= link_to restaurant_path(restaurant) do %>
            <div class="my-restaurant">
              <div>
                <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
              </div>
              <h5><%= restaurant.name %></h5>
            </div>
            <% end %>

            <% end %>
          </div>
        </div>

        <!-- 顯示收藏的餐廳的清單，panel包一個panel-body裡面簡單顯示餐廳圖片和name -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
          </div>

          <div class="panel-body">
            <% @favorited_restaurants.each do |restaurant| %>
              <div class="my-restaurant">
                <div>
                  <%= link_to restaurant_path(restaurant) do %>
                    <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
                    <h5><%= restaurant.name %></h5>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

      </div>


    </div>
  </div>
</div>