config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  mount ActionCable.server => '/cable'
  devise_for :users,path_names: {sign_in:'login',sign_out:'logout',sign_up:'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :restaurants, only: [:index, :show] do
  resources :comments, only: [:create, :destroy]
  collection do
    get :feeds
    get :ranking
  end
  member do
    get :dashboard
    post :favorite
    post :unfavorite
    post :like
    post :unlike
  end
end
resources :categories, only: :show

resources :users, only: [:index, :update, :show, :edit] do
  member do
    get :friend_list
  end
end


resources :followships, only: [:create, :destroy]

resources :friendships, only: [:create, :destroy]

root "restaurants#index"
namespace :admin do
    root "restaurants#index"
    resources :restaurants
    resources :categories 
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
validates_presence_of :name
has_many :restaurants, dependent: :restrict_with_error




end

app/models/comment.rb
class Comment < ApplicationRecord

belongs_to :user
belongs_to :restaurant




end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord

  validates :following_id, uniqueness: { scope: :user_id}




  belongs_to :user
  belongs_to :following, class_name: "User"




end

app/models/friendship.rb
class Friendship < ApplicationRecord

  validates :friend_id, uniqueness: { scope: :user_id}

  belongs_to :user
  belongs_to :friend, class_name: "User"




end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates_presence_of :name
  mount_uploader :image, PhotoUploader
  belongs_to :category
  has_many :comments  , dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user






  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


  def count_favorites
    self.favorite_count = self.favorites.size
    self.save
  end


  def is_liked?(user)
    self.liked_users.include?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


mount_uploader :avatar, AvatarUploader
# 「使用者評論很多餐廳」的多對多關聯
has_many :comments, dependent: :restrict_with_error
has_many :restaurants, through: :comments
 # 「使用者收藏很多餐廳」的多對多關聯
has_many :favorites, dependent: :destroy
has_many :favorited_restaurants, through: :favorites, source: :restaurant

has_many :lkes, dependent: :destroy
has_many :liked_restaurants, through: :likes, source: :restaurant 
 # 「使用者追蹤使用者」的 self-referential relationships 設定
 # 不需要另加 source，Rails 可從 Followship Model 設定來判斷 followings 指向 User Model
has_many :followships, dependent: :destroy
has_many :followings, through: :followships
 # 透過 class_name, foreign_key 的自訂，指向 Followship 表上的另一側
has_many :inverse_followships, class_name: "Followship",foreign_key: "following_id"
has_many :followers, through: :inverse_followships, source: :user

has_many :friendships, dependent: :destroy
has_many :friends, through: :friendships

has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id" #反向的交友關係 fk為friend_id

has_many :inverse_friends, through: :inverse_friendships, source: :user #加我好友的人



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    def admin?
    self.role == "admin"
  
    end

    def following?(user)
      self.followings.include?(user)
    end

    def friending?(user)
      self.friends.include?(user)

    end

    

    def all_friends?(user)
      self.friends.include?(user) || self.inverse_friends.include?(user)
    end

    def friends?(user)
    self.friends.include?(user)
    end
    def inverse_friends?(user)
      self.inverse_friends.include?(user)
    end

    
    def friends_list
    list = []
    self.friends.each do |friend|
      list<<friend if self.inverse_friends.include?(friend)
    end
    return list
    end 


validates_presence_of :name
 
    def first_name
       self.name.split.first
    end
    def last_name
     self.name.split.last_name
    end







end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :friend_list]
  
  def index
  @users= User.all
  
  end 



  def show 
    @commented_restaurants = @user.restaurants
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers  =@user.followers
    @friends = @user.friends_list
    @inverse_friends =  @user.inverse_friends
  end


  def edit

    unless @user ==current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  def friend_list
     @friends = @user.friends
     @inverse_friends =  @user.inverse_friends
  end
  def friend_list
    @user = User.find(params[:id])
    # @all_friends = @user.all_friends
    @friends_list = @user.friends_list
    @sendrequests = @user.friends - @friends_list
    #去除已經加入好友的名單
    @getrequests = @user.inverse_friends - @friends_list
    #去除已經加入好友的名單
  end

  private

    def set_user
      @user = User.find(params[:id])
    end


    def user_params
      params.require(:user).permit(:name, :intro, :avator)
    end

  



 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    
    <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to'餐廳評論網',restaurants_path,class: "navbar-brand" %>
    </div>
      
      <ul class="nav navbar-nav navbar-right">
                
        <% if current_user%>
                  <% if current_user.admin? %>
                      <li><%= link_to 'Admin後台', admin_restaurants_path,class: "active"%></li>
                    <% end %>
                  
                  
                  <p class="navbar-text"><%= current_user.first_name %></p>
                  <li><%= link_to 'Profile', user_path(current_user),class: "glyphicon glyphicon-user"%></li>
                  <li><%= link_to '修改密碼', edit_user_registration_path(current_user),class: "active"%></li>
                  <li><%= link_to "Logout",destroy_user_session_path,method: :delete, class: "glyphicon glyphicon-log-out"  %></li>
                  
      </ul>           
                 

      


     <%= form_tag restaurants_path, method: :get,class: "navbar-form navbar-left"  do%>
        <%= text_field_tag :search ,params[:search],placeholder:"Enter text..", class: "form-control"%>
        <%= submit_tag "搜尋"  ,name: nil,class: "btn btn-default"%>
        <%end%>

    
      
      <% end %>

  </nav>
  
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



    <%= yield %>
  </body>
</html>

app/views/shared/_addfriend.erb
<% if user != current_user %>
  <% if current_user.friends?(user) %>
    <%= link_to '解除好友', friendship_path(user), method: :delete , class:"btn btn-link"%>
  <%else%>
    <%= link_to '加好友', friendships_path(friend_id: user), method: :post, class:"btn btn-default" %>
  <%end%>
<%end%>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user)%>
   <%= link_to 'Unfollow', followship_path(user), method: :delete ,class: "btn btn-info"%>
  <% else %>
   <%= link_to 'Follow', followships_path(following_id: user), method: :post,class: "btn btn-default"%>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user  %>
  
  <% if current_user.all_friends?(user)%>
    <% if current_user.inverse_friends?(user)%>
      <%= link_to "好友", friendship_path(user), method: :delete , class: "btn btn-info"%>
    <% else%>
      <%= link_to "等待回覆", friendship_path(user), method: :delete %>
    <%end%>
  <% else %>
  <%= link_to "加好友", friendships_path(friend_id: user), method: :post, class: "btn btn-default"%>
  <% end %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="restaurant-item">
          <%= image_tag restaurant.image, class: "img-responsive center-block" %>
          <div class="caption">
            <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p class="label label-default"><%= restaurant.category.name %><p>
            <p><%= truncate(restaurant.description, length: 80) %></p>
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
          </div>
        </div>
      </div>
    <% end %>
      
    <!-- 有generate kaminari paginate bootstrap style -->
    <% if params[:search]%>
    
    <%else %>
      <div class="text-center">
        <%= paginate @restaurants %>
      </div>
      <%end%>

app/views/shared/_user_list.erb
<%users.each do |user| %>
  <p><%=link_to user.name, user_path(user)%></p>
  <%= render partial: "shared/follow",locals:{user: user} %>
  <%= render partial: "shared/addfriend",locals:{user: user} %>

<%end%>